from uuid import UUID
from typing import Protocol

class SecurityEventPublisher(Protocol):

    async def login_success(self, user_id: UUID): ...

    async def login_failure(self, identifier: str): ...

    async def otp_failed(self, user_id: UUID): ...

    async def account_locked(self, user_id: UUID): ...